### ISSUE TITLE
MSB806 Error

### ISSUE THREAD

**Issue by user-guigu** [TheWayYo/DiffFrameworkDemo#2]
错误	MSB8066、
说明:“E:\ncnn\ncnn-master\build\CMakeFiles\1b1db7e45685cdf648a204ba94747efa\caffe.pb.h.rule;E:\ncnn\ncnn-master\tools\caffe\CMakeLists.txt”的自定义生成已退出，代码为 -1073741515。	
项目	：caffe2ncnn	
文件：D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	
行：241	

错误	MSB8066	
说明:“E:\ncnn\ncnn-master\build\CMakeFiles\28fedb3ee9fe9ddcd15283bb6cdc5cb0\onnx.pb.h.rule;E:\ncnn\ncnn-master\tools\onnx\CMakeLists.txt”的自定义生成已退出，代码为 -1073741515。	
项目	：onnx2ncnn	
文件：D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	
行：241	

在ncnn生成ALL_BUILD时，出现上述两个错误。请问这会是什么原因导致的？我又该如何解决呢？

**Comment by TheWayYo** [comment]
caffe2ncnn和onnx2ncnn编译失败大概率是因为protobuf没有正确编译，看看报错信息是不是有protobuf相关的错误，如果不必须在windows使用caffe2ncnn和onnx2ncnn的话，可以在linux下转好模型，windows编译好有ncnn.lib和ncnn.dll就可以了

**Comment by user-guigu** [comment]
的确是protobuf没能正确编译的问题，谢谢。
